name: markslee
favicon: null
layout_spectrum: 0.24179
typography_spectrum: 0.8162846106570214
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.20114846853539348
  lightness: 0.6380347835365683
  saturation: 0.017827158328145742
  rhythmicContrast: 0.5653714402578771
purpose: []
